name: Deploy SB App to EC2

on:
  push:
    branches:
      - master  # Ensure your branch is really called master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo pkill -f 'java -jar' || true
            sudo rm -rf SB-APP

            # Cloning the repo using PAT
            git clone https://varunkanneganti125:${{ secrets.MY_GIT_PAT }}@github.com/varunkanneganti125/SB-APP.git
            cd SB-APP || exit 1

            ./mvnw clean package -DskipTests

            JAR_FILE=$(ls target/*.jar | head -n 1)
            if [ -z "$JAR_FILE" ]; then
              echo "No JAR file found"
              exit 1
            fi

            nohup java -jar "$JAR_FILE" > app.log 2>&1 &
            echo "✅ Spring Boot app deployed successfully"

            sudo systemctl restart httpd || true  # Only if using Apache
          EOF
